Replace Travis CI/Appveyor with GitHub Actions
doyubkim/fluid-engine-dev pull request #314
Opened 2021-02-09 12:25 UTC by utilForever

This replaces Travis CI and Appveyor with GitHub Actions (#312).

2021-02-09 14:57 UTC, utilForever commented
@doyubkim You should 'Required' mark of 'Appveyor' and 'Travis CI'. Also, I removed Appveyor configuration file. So, you should delete this repo from Appveyor.

2021-02-10 06:39 UTC, doyubkim requested changes
Other then my inline comments, it would be nice to add with/without TBB as part of the build matrix. Also, would it be possible to add MinGW test for Windows?

2021-02-10 06:39 UTC, doyubkim commented on .github/workflows/codeql-analysis.yml
> +    - cron: '0 15 * * 5'
I don't think we need this to be a cron job. Triggering this action when push to main and PR to main occurs should be enough.

2021-02-10 06:39 UTC, doyubkim commented on .github/workflows/macos.yml
> +          - name: "macOS 10.15 + Xcode 11.7"
Rather then testing multiple compilers in a single macOS, it would be better to test with multiple macOS versions with their latest Xcode versions. We should support from whatever the oldest macOS version the Github Action supports.

2021-02-10 06:39 UTC, doyubkim commented on .github/workflows/macos.yml
> +          - name: "macOS 10.15 + gcc-8"
Same here. Testing with gcc is nice, but let's just pick the latest version per macOS version.

2021-02-10 06:39 UTC, doyubkim commented on .github/workflows/ubuntu.yml
> +          - name: "Ubuntu 18.04 + gcc-8"
In case of Ubuntu, let's pick the "default" version of gcc/clang that gets installed via apt-get.

2021-02-10 06:39 UTC, doyubkim commented on .github/workflows/windows.yml
> +          - name: "Windows Server 2019 + Visual Studio 2019"
We should test with older versions if possible.

2021-02-10 06:39 UTC, doyubkim commented on .github/workflows/ubuntu.yml
> +        python3 -m pytest src/tests/python_tests/
nit: newline at the end of the file.

2021-02-12 13:16 UTC, utilForever commented on .github/workflows/codeql-analysis.yml
> +    - cron: '0 15 * * 5'
Alright. I'll delete this line.

2021-02-12 13:25 UTC, utilForever commented on .github/workflows/windows.yml
> +          - name: "Windows Server 2019 + Visual Studio 2019"
When I build "Windows Server 2016 + Visual Studio 2017", I saw the error below:
```
LINK : the 32-bit linker (C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.16.27023\bin\HostX86\x64\link.exe) ran out of heap space and is going to restart linking with a 64-bit linker
  LINK : restarting link with 64-bit linker `C:\Program Files\Git\usr\bin\link.exe'
  /c/Program Files (x86)/Microsoft Visual Studio/2017/Enterprise/VC/Tools/MSVC/14.16.27023/bin/HostX86/x64/link: cannot create link ' ■/' to '/ERRORREPORT:QUEUE': No such file or directory
C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(720,5): error MSB6006: "link.exe" exited with code 1. 
```
I saw this error in CubbyFlow, however, I don't know why it occurs. So, I disabled this build temporarily and I'll resolve this error soon.

2021-02-12 13:26 UTC, utilForever commented on .github/workflows/ubuntu.yml
> +        python3 -m pytest src/tests/python_tests/
Okay. I'll resolve it.

2021-02-12 13:33 UTC, utilForever commented on .github/workflows/macos.yml
> +          - name: "macOS 10.15 + Xcode 11.7"
Currently, GitHub Action supports 'macos-10.15' and 'macos-11.0'. (https://github.com/actions/virtual-environments)
I'll check latest Xcode version and change it.

2021-02-12 13:34 UTC, utilForever commented on .github/workflows/macos.yml
> +          - name: "macOS 10.15 + gcc-8"
Alright. I'll check latest gcc version and change it.

2021-02-12 13:34 UTC, utilForever commented on .github/workflows/ubuntu.yml
> +          - name: "Ubuntu 18.04 + gcc-8"
Alright. I'll check default gcc version and change it.

2021-02-13 08:38 UTC, doyubkim requested changes
We also need to update the badge in README.md

2021-02-13 08:43 UTC, utilForever commented
@doyubkim I'm trying to build Windows-MinGW. Please wait. 😢

2021-02-13 08:46 UTC, utilForever commented on .github/workflows/macos.yml
> +
The macOS 11.0 virtual environment is currently provided as a private preview only. So, I deleted it.

2021-02-14 02:53 UTC, doyubkim commented on .github/workflows/ubuntu.yml
> +      run: /home/runner/work/fluid-engine-dev/fluid-engine-dev/build/bin/unit_tests
Is there any environment variable for such paths? At least for the first couple of parent directories.

2021-02-14 02:53 UTC, doyubkim commented on .github/workflows/windows.yml
> +      run: /a/fluid-engine-dev/fluid-engine-dev/build/bin/Release/unit_tests.exe
Same here. The absolute path makes me a bit nervous. Is there any environment variable.

2021-02-15 16:24 UTC, utilForever commented on .github/workflows/ubuntu.yml
> +      run: /home/runner/work/fluid-engine-dev/fluid-engine-dev/build/bin/unit_tests
I'll change it.

2021-02-15 16:24 UTC, utilForever commented on .github/workflows/windows.yml
> +      run: /a/fluid-engine-dev/fluid-engine-dev/build/bin/Release/unit_tests.exe
I'll change it.

2021-02-15 16:28 UTC, utilForever commented on .github/workflows/macos.yml
> +            version: "12.4"
I'll change Xcode 11.2.1 that supports minimum version.

2021-02-15 16:29 UTC, utilForever commented on .github/workflows/macos.yml
> +          sudo xcode-select -switch /Applications/Xcode_${{ matrix.version }}.app
Yes, because the default version of `macos-10.15` is Xcode 12.3.
(References: https://github.com/actions/virtual-environments/blob/main/images/macos/macos-10.15-Readme.md)

2021-02-15 16:29 UTC, utilForever commented on .github/workflows/macos.yml
> +        python-version: '3.7'
I'll change it.

2021-02-16 01:18 UTC, doyubkim requested changes
As mentioned before, please update the README's badges as well. I think the only remaining blocker is the missing macOS 11 build.

2021-02-16 01:18 UTC, doyubkim commented on .github/workflows/codeql-analysis.yml
> +# For most projects, this workflow file will not need changing; you simply need
From where did this config comes from? (Looks like it is based on a template.) Please add the reference to the original file.

2021-02-16 01:18 UTC, doyubkim commented on .github/workflows/macos.yml
> +        include:
Sorry if I missed your comments but I think you're missing macOS 11. The 10.15 setting looks good now.

2021-02-16 01:18 UTC, doyubkim commented on .github/workflows/windows.yml
> +          # Windows Server 2016 + Visual Studio 2017
Can you open another issue for following up with this problem?

2021-02-16 01:21 UTC, utilForever commented on .github/workflows/macos.yml
> +        include:
The macOS 11.0 virtual environment is currently provided as a private preview only. So, I deleted it.

2021-02-16 01:22 UTC, utilForever commented on .github/workflows/windows.yml
> +          # Windows Server 2016 + Visual Studio 2017
Okay, I'll open issue for this problem.

2021-02-16 01:30 UTC, utilForever commented on .github/workflows/codeql-analysis.yml
> +# For most projects, this workflow file will not need changing; you simply need
This is a standard template for "GitHub CodeQL Analysis". I'll add reference.

2021-02-16 02:54 UTC, doyubkim commented on .github/workflows/macos.yml
> +        include:
😧 wow ok. GA seems to be a bit behind in terms of its image collection I guess. Thanks!

2021-02-16 02:55 UTC, doyubkim approved these changes
Looks good now. Thanks for the hard work!

2021-02-16 03:53 UTC, merged